[project]
name = "codebase-onboarding"
version = "0.1.0"
description = "AI Onboarding Buddy"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "PyGithub",
    "python-dotenv",
    "requests",
    "pandas",
    "openai",
    "langgraph",
    "langchain",
    "langchain-openai",
    "langchain-community",
    "chromadb",
    "networkx"
]
